add step for test

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -18,5 +18,8 @@ jobs:
         with:
           go-version: "1.26.0"
 
-      - name: Force Failure
-        run: (exit 1)
+      - name: Test Go
+        run: go test ./...
+      #
+      # - name: Force Failure
+      #   run: (exit 1)
